# Generated by Django 3.2.8 on 2024-11-14 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('colegio', '0036_appearancesettings_comunicados_card_transparency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoDewey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialBibliografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('resumen', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='materiales')),
                ('cantidad', models.IntegerField(default=1)),
                ('edad_recomendada', models.CharField(blank=True, default='0', max_length=10)),
                ('volumen', models.PositiveIntegerField(blank=True, help_text='Número de volumen si es una obra de varios tomos', null=True)),
                ('numero_copia', models.PositiveIntegerField(default=1, help_text='Número de copia del ejemplar')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('autores', models.ManyToManyField(related_name='materiales', to='biblioteca.Autor')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dewey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.codigodewey')),
                ('editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=255)),
                ('grado', models.CharField(max_length=100)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tesis', to='biblioteca.materialbibliografico')),
            ],
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=8, unique=True)),
                ('volumen', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revista', to='biblioteca.materialbibliografico')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='prestado', max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='colegio.alumno')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.materialbibliografico')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='libro', to='biblioteca.materialbibliografico')),
            ],
        ),
        migrations.CreateModel(
            name='Fanzine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edicion', models.CharField(blank=True, max_length=50)),
                ('tema', models.CharField(max_length=100)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fanzine', to='biblioteca.materialbibliografico')),
            ],
        ),
        migrations.CreateModel(
            name='CampoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_adicionales', to='biblioteca.materialbibliografico')),
            ],
            options={
                'unique_together': {('material', 'nombre')},
            },
        ),
    ]
