# Generated by Django 3.2.8 on 2024-11-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={'ordering': ['nombre'], 'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.RemoveField(
            model_name='materialbibliografico',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='materialbibliografico',
            name='numero_copia',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='material',
        ),
        migrations.AddField(
            model_name='materialbibliografico',
            name='total_copias',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_copia', models.PositiveIntegerField()),
                ('estado', models.CharField(default='disponible', max_length=50)),
                ('fecha_adquisicion', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='biblioteca.materialbibliografico')),
            ],
            options={
                'unique_together': {('material', 'numero_copia')},
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='ejemplar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.ejemplar'),
            preserve_default=False,
        ),
    ]
