# Generated by Django 3.2.8 on 2025-04-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20241117_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=100)),
                ('apellido_profesor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('bloque', models.CharField(choices=[('1', '8:30 - 10:00'), ('2', '10:20 - 11:45'), ('3', '12:00 - 13:30'), ('4', '14:15 - 15:45')], max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha', 'bloque'],
                'unique_together': {('fecha', 'bloque')},
            },
        ),
    ]
