# Generated by Django 3.2.8 on 2025-04-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_reservacomputador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservaComputador',
            new_name='Reserva',
        ),
    ]
