# Generated by Django 3.2.8 on 2025-05-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_rename_reservacomputador_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='necesita_computadores',
            field=models.BooleanField(default=False, verbose_name='¿Necesita computadores?'),
        ),
    ]
