# Generated by Django 3.2.8 on 2025-05-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_reserva_necesita_computadores'),
    ]

    operations = [
        # Agregar índices para mejorar el rendimiento de consultas
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_materialbibliografico_titulo ON biblioteca_materialbibliografico(titulo);",
            reverse_sql="DROP INDEX IF EXISTS idx_materialbibliografico_titulo;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_ejemplar_estado ON biblioteca_ejemplar(estado);",
            reverse_sql="DROP INDEX IF EXISTS idx_ejemplar_estado;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_ejemplar_material_estado ON biblioteca_ejemplar(material_id, estado);",
            reverse_sql="DROP INDEX IF EXISTS idx_ejemplar_material_estado;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_autor_nombre ON biblioteca_autor(nombre);",
            reverse_sql="DROP INDEX IF EXISTS idx_autor_nombre;"
        ),
    ]
