# Generated by Django 4.2 on 2023-12-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='noticias/audios'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
