# Generated by Django 4.2 on 2023-05-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_images_noticia_delete_profesor_images_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='tema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
