# Generated by Django 4.2 on 2023-05-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_remove_images_noticia_noticia_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='images',
        ),
        migrations.AddField(
            model_name='images',
            name='noticia',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='colegio.noticia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
