# Generated by Django 4.2 on 2023-05-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0005_remove_noticia_images_images_noticia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Comunicados', max_length=50)),
                ('background', models.CharField(default='rgba(132, 158, 214, 0.65)', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Comunicados')),
            ],
        ),
    ]
