# Generated by Django 4.2 on 2023-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0007_comunicado_alter_comunicados_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=600)),
            ],
        ),
    ]
