# Generated by Django 4.2 on 2023-05-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0012_alter_evento_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
    ]
