# Generated by Django 4.2 on 2023-06-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0014_colegio_telefono_alter_evento_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='horario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
