# Generated by Django 4.2 on 2023-07-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0015_colegio_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
