# Generated by Django 4.2 on 2023-08-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0016_delete_images_delete_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
