# Generated by Django 4.2 on 2023-08-16 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0020_alter_asignatura_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='asignaturas',
        ),
    ]
