# Generated by Django 4.2 on 2023-08-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0021_remove_curso_asignaturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='profesor',
        ),
    ]
