# Generated by Django 4.2 on 2023-09-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0024_remove_archivoscomunicado_comunicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jefe',
            field=models.BooleanField(default=False),
        ),
    ]
