# Generated by Django 5.0.6 on 2024-06-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0027_menuitem_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='school_name',
        ),
    ]
