# Generated by Django 5.0.6 on 2024-10-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0028_remove_menu_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='eventos_card_background',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='eventos_card_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
