# Generated by Django 5.0.6 on 2024-10-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0029_appearancesettings_eventos_card_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='jefe',
        ),
        migrations.AddField(
            model_name='profesor',
            name='jefe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('profesor', 'Profesor'), ('asistente', 'Asistente'), ('alumno', 'Alumno'), ('apoderado', 'Apoderado')], max_length=50),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colegio.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.curso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colegio.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnos', models.ManyToManyField(related_name='apoderados', to='colegio.alumno')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colegio.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colegio.userprofile')),
            ],
        ),
    ]
