# Generated by Django 5.0.6 on 2024-10-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0030_remove_profesor_nombre_remove_userprofile_jefe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='comunicados_background',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
