# Generated by Django 5.0.6 on 2024-10-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0031_appearancesettings_comunicados_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='profesores_background',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
