# Generated by Django 5.0.6 on 2024-11-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0032_appearancesettings_profesores_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['orden']},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='menu',
            name='nombre',
            field=models.CharField(default='Menu Principal', max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='es_mega_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='colegio.menu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, default='img/default-profile.png', null=True, upload_to='profile_photos/'),
        ),
    ]
