# Generated by Django 5.0.6 on 2024-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0034_default_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='comunicados_card_background',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
