# Generated by Django 5.0.6 on 2024-11-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0035_appearancesettings_comunicados_card_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='comunicados_card_transparency',
            field=models.IntegerField(default=0),
        ),
    ]
