# Generated by Django 5.0.6 on 2025-06-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0036_appearancesettings_comunicados_card_transparency'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='solo_usuarios_logueados',
            field=models.BooleanField(default=False),
        ),
    ]
