# Generated by Django 5.0.6 on 2025-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0038_preguntafrecuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='usar_color_principal',
            field=models.BooleanField(default=True, help_text='Activar para que los botones primary usen el color principal del sitio'),
        ),
    ]
