# Generated by Django 5.0.6 on 2025-07-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0039_appearancesettings_usar_color_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='56912345678', help_text='Número de WhatsApp para contacto (incluir código de país sin +). Ejemplo: 56912345678', max_length=20, null=True),
        ),
    ]
