# Generated by Django 5.0.6 on 2025-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0040_appearancesettings_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icono',
            field=models.ImageField(blank=True, help_text='Imagen pequeña que aparecerá junto al nombre del item en el menú', null=True, upload_to='menu_icons/'),
        ),
    ]
