# Generated by Django 5.0.6 on 2025-07-11 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0041_menuitem_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='icono',
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la sección hero (recomendado: 1920x1080px)', null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='hero_btn_primary_text',
            field=models.CharField(default='Conoce Más', help_text='Texto del botón principal', max_length=50),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='hero_btn_secondary_text',
            field=models.CharField(default='Ver Comunicados', help_text='Texto del botón secundario', max_length=50),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='hero_enable_parallax',
            field=models.BooleanField(default=True, help_text='Activar efecto parallax en el hero'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='hero_overlay_opacity',
            field=models.FloatField(default=0.4, help_text='Opacidad del overlay oscuro (0.0 = transparente, 1.0 = opaco)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='hero_subtitle',
            field=models.TextField(default='Formando líderes del futuro con excelencia académica y valores sólidos', help_text='Subtítulo del hero', max_length=500),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='hero_subtitle_color',
            field=models.CharField(default='#FFFFFF', help_text='Color del subtítulo', max_length=7),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='hero_title',
            field=models.CharField(default='Bienvenidos a Nuestro Colegio', help_text='Título principal del hero', max_length=200),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='hero_title_color',
            field=models.CharField(default='#FFFFFF', help_text='Color del título principal', max_length=7),
        ),
    ]
