# Generated by Django 5.0.6 on 2025-07-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0042_remove_menuitem_icono_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearancesettings',
            options={'verbose_name': 'Configuración de Apariencia', 'verbose_name_plural': 'Configuraciones de Apariencia'},
        ),
    ]
