# Generated by Django 5.0.6 on 2025-07-11 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0043_alter_appearancesettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Imagen de fondo para la sección hero (recomendado: 1920x1080px)', null=True, upload_to='hero/')),
                ('title', models.CharField(default='Bienvenidos a Nuestro Colegio', help_text='Título principal del hero', max_length=200)),
                ('subtitle', models.TextField(default='Formando líderes del futuro con excelencia académica y valores sólidos', help_text='Subtítulo del hero', max_length=500)),
                ('title_color', models.CharField(default='#FFFFFF', help_text='Color del título principal', max_length=7)),
                ('subtitle_color', models.CharField(default='#FFFFFF', help_text='Color del subtítulo', max_length=7)),
                ('btn_primary_text', models.CharField(default='Conoce Más', help_text='Texto del botón principal', max_length=50)),
                ('btn_secondary_text', models.CharField(default='Ver Comunicados', help_text='Texto del botón secundario', max_length=50)),
                ('btn_primary_url', models.CharField(default='#noticias', help_text='URL del botón principal (usar # para anclas)', max_length=200)),
                ('btn_secondary_url', models.CharField(default='/comunicados/', help_text='URL del botón secundario', max_length=200)),
                ('overlay_opacity', models.FloatField(default=0.4, help_text='Opacidad del overlay oscuro (0.0 = transparente, 1.0 = opaco)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('enable_parallax', models.BooleanField(default=True, help_text='Activar efecto parallax en el hero')),
                ('height_desktop', models.CharField(default='100vh', help_text='Altura en desktop (ej: 100vh, 800px)', max_length=10)),
                ('height_mobile', models.CharField(default='100vh', help_text='Altura en móvil (ej: 100vh, 600px)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Activar/desactivar la sección hero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Hero',
                'verbose_name_plural': 'Configuraciones Hero',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='hero_btn_primary_text',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='hero_btn_secondary_text',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='hero_enable_parallax',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='hero_overlay_opacity',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='hero_subtitle_color',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='hero_title_color',
        ),
    ]
