# Generated by Django 5.0.6 on 2025-07-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0044_herosettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosettings',
            name='enable_parallax',
        ),
        migrations.RemoveField(
            model_name='herosettings',
            name='height_desktop',
        ),
        migrations.RemoveField(
            model_name='herosettings',
            name='height_mobile',
        ),
        migrations.RemoveField(
            model_name='herosettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='herosettings',
            name='overlay_opacity',
        ),
    ]
