# Generated by Django 5.0.6 on 2025-07-12 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0045_remove_herosettings_enable_parallax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='mega_menu_font_bold',
            field=models.BooleanField(default=False, help_text='Activar para texto en negrita'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='mega_menu_font_size',
            field=models.PositiveIntegerField(default=14, help_text='Tamaño de fuente en píxeles (12-20)', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='menu_font_bold',
            field=models.BooleanField(default=False, help_text='Activar para texto en negrita'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='menu_font_size',
            field=models.PositiveIntegerField(default=16, help_text='Tamaño de fuente en píxeles (12-24)', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
