# Generated by Django 5.0.6 on 2025-07-13 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0046_appearancesettings_mega_menu_font_bold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearancesettings',
            name='mega_menu_font_bold',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='mega_menu_font_size',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='menu_font_bold',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='menu_font_size',
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Imagen de fondo principal para la sección hero (recomendado: 1920x1080px)', null=True, upload_to='hero/'),
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen adicional para el hero (recomendado: 1920x1080px)', upload_to='hero/additional/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número aparece primero)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='colegio.herosettings')),
            ],
            options={
                'verbose_name': 'Imagen del Hero',
                'verbose_name_plural': 'Imágenes del Hero',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
