# Generated by Django 5.0.6 on 2025-07-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0047_remove_appearancesettings_mega_menu_font_bold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='pais',
            field=models.CharField(blank=True, default='Chile', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
