# Generated by Django 5.0.6 on 2025-07-14 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0048_colegio_pais_colegio_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColegioSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_noticias_enabled', models.BooleanField(default=False)),
                ('openai_comunicados_enabled', models.BooleanField(default=False)),
                ('openai_biblioteca_enabled', models.BooleanField(default=False)),
                ('monthly_limit', models.IntegerField(default=0)),
                ('current_usage', models.IntegerField(default=0)),
                ('period_start', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Configuración de Suscripción IA',
                'verbose_name_plural': 'Configuraciones de Suscripción IA',
            },
        ),
    ]
