# Generated by Django 5.0.6 on 2025-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0049_colegiosubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL completa de la página de Facebook del colegio', null=True),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL completa de la cuenta de Instagram del colegio', null=True),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='URL completa de la cuenta de Twitter/X del colegio', null=True),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL completa del canal de YouTube del colegio', null=True),
        ),
    ]
