# Generated by Django 5.0.6 on 2025-07-16 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0050_appearancesettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrativo', 'Administrativo'), ('profesor', 'Profesor'), ('asistente', 'Asistente'), ('alumno', 'Alumno'), ('apoderado', 'Apoderado')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='colegio.userprofile')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'unique_together': {('user_profile', 'role')},
            },
        ),
    ]
